<a href="https://colab.research.google.com/github/OjashShakya/Ojash_Shakya_2408654_AI_Worksheets/blob/main/2408654_OjashShakya_Worksheet_W0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Name: Ojash Shakya
### ID: 2408654

# Review on Python and Numpy for Deep Learning

 ## TO-DO-Task

### Exercise on Functions:



Task- 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).

2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).

In [119]:
# Unit Converter Program

def convert_units(conversion_type, value):
    """
    Converts a value between different measurement units.

    Parameters:
    conversion_type (str): Type of conversion (m_to_ft, ft_to_m, kg_to_lb,
                           lb_to_kg, l_to_gal, gal_to_l).
    value (float): The value that needs to be converted.

    Returns:
    float: Converted value based on the selected conversion type.
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lb":
        return value * 2.20462
    elif conversion_type == "lb_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172

print("\nLength Conversion")
print("1. Meters (m) to Feet (ft)")
print("2. Feet (ft) to Meters (m)")

print("\nWeight Conversion")
print("3. Kilograms (kg) to Pounds (lbs)")
print("4. Pounds (lbs) to Kilograms (kg)")

print("\nVolume Conversion")
print("5. Liters (L) to Gallons (gal)")
print("6. Gallons (gal) to Liters (L)")

try:
    choice = int(input("\nEnter your choice (1-6): "))
    value = float(input("Enter the value to convert: "))

    if choice == 1:
        result = convert_units("m_to_ft", value)
    elif choice == 2:
        result = convert_units("ft_to_m", value)
    elif choice == 3:
        result = convert_units("kg_to_lb", value)
    elif choice == 4:
        result = convert_units("lb_to_kg", value)
    elif choice == 5:
        result = convert_units("l_to_gal", value)
    elif choice == 6:
        result = convert_units("gal_to_l", value)
    else:
        print("Error: Unsupported conversion type.")
        result = None

    if result is not None:
        print("Converted value:", result)

except ValueError:
    print("Error: Invalid input. Please enter numeric values.")


Length Conversion
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)

Weight Conversion
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)

Volume Conversion
5. Liters (L) to Gallons (gal)
6. Gallons (gal) to Liters (L)

Enter your choice (1-6): 1
Enter the value to convert: 1.8
Converted value: 5.905512


Task- 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces)
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [120]:
# Program to perform mathematical operations on a list of numbers

def find_sum(numbers):
    """
    Calculate the sum of numbers in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of all numbers in the list.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of numbers in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers in the list.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)

print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")

try:
    choice = int(input("Enter your choice (1-4): "))

    numbers_input = input("Enter numbers separated by spaces: ")

    if not numbers_input.strip():
        raise ValueError("Empty list is not allowed.")

    numbers = [float(num) for num in numbers_input.split()]

    if choice == 1:
        result = find_sum(numbers)
        print("Sum:", result)

    elif choice == 2:
        result = find_average(numbers)
        print("Average:", result)

    elif choice == 3:
        result = find_maximum(numbers)
        print("Maximum:", result)

    elif choice == 4:
        result = find_minimum(numbers)
        print("Minimum:", result)

    else:
        print("Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numeric values and a non-empty list.")

1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 1 2
Sum: 3.0


### Exercise on List Manipulation:




Sample List: [1, 2, 3, 4, 5, 6]

In [121]:
sample_list = [1, 2, 3, 4, 5, 6]

print("Original List:", sample_list)

Original List: [1, 2, 3, 4, 5, 6]


1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract
every
other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].



In [122]:
def extract_every_other(lst):
    """
    Extract every other element from the list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]

print("Every other element:", extract_every_other(sample_list))

Every other element: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get
sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].



In [123]:
def get_sublist(lst, start, end):
    """
    Return a sublist from start index to end index (inclusive).

    Parameters:
    lst (list): The input list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: Sublist from start to end.
    """
    return lst[start:end+1]

print("Sublist (2 to 4):", get_sublist(sample_list, 2, 4))

Sublist (2 to 4): [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse
slicing.
list(lst) that takes a list lst and returns a reversed list using

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1]



In [124]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: Reversed list.
    """
    return lst[::-1]

print("Reversed list:", reverse_list(sample_list))

Reversed list: [6, 5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Defineafunction remove
first
last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].



In [125]:
def remove_first_last(lst):
    """
    Remove the first and last elements of the list.

    Parameters:
    lst (list): The input list.

    Returns:
    list: List without the first and last elements.
    """
    return lst[1:-1]

print("Without first and last:", remove_first_last(sample_list))

Without first and last: [2, 3, 4, 5]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get
first
n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].



In [126]:
def get_first_n(lst, n):
    """
    Get the first n elements of a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: First n elements of the list.
    """
    return lst[:n]

print("First 3 elements:", get_first_n(sample_list, 3))

First 3 elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get
last
n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].



In [127]:
def get_last_n(lst, n):
    """
    Get the last n elements of a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: Last n elements of the list.
    """
    return lst[-n:]

print("Last 2 elements:", get_last_n(sample_list, 2))

Last 2 elements: [5, 6]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse
skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]

In [128]:
def reverse_skip(lst):
    """
    Extract elements in reverse order starting from the second-to-last
    element and skipping one element each time.

    Parameters:
    lst (list): The input list.

    Returns:
    list: New list with elements selected in reverse skipping pattern.
    """
    return lst[-2::-2]

print("Reverse skip:", reverse_skip(sample_list))

Reverse skip: [5, 3, 1]


### Exercise on Nested List:


1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [129]:
def flatten(lst):
    """
    Flatten a nested list into a single list (one level).

    Parameters:
    lst (list): Nested list.

    Returns:
    list: Flattened list.
    """
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result

lst = [[1, 2], [3, 4], [5]]
print("Flatten:", flatten(lst))

Flatten: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access
nested
element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.


In [130]:
def access_nested_element(lst, indices):
    """
    Access a specific element in a nested list using a list of indices.

    Parameters:
    lst (list): Nested list.
    indices (list): List of indices to access the element.

    Returns:
    element at the specified position.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
indices = [1,2]

print("Access element:", access_nested_element(lst, indices))

Access element: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum
nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.


In [131]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list (any depth).

    Parameters:
    lst (list): Nested list.

    Returns:
    int/float: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

lst = [[1,2],[3,[4,5]],6]
print("Sum nested:", sum_nested(lst))

Sum nested: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove
element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
be [[1], [3], [4, 5]].


In [132]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): Nested list.
    elem : Element to remove.

    Returns:
    list: Modified list without the specified element.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

lst = [[1,2],[3,2],[4,5]]
print("Remove element:", remove_element(lst, 2))

Remove element: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find
element.
max(lst) that takes a nested list lst and returns the maximum

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.


In [133]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
    lst (list): Nested list.

    Returns:
    int/float: Maximum value.
    """
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

lst = [[1,2],[3,[4,5]],6]
print("Max element:", find_max(lst))

Max element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
be 3.


In [134]:
def count_occurrences(lst, elem):
    """
    Count occurrences of an element in a nested list.

    Parameters:
    lst (list): Nested list.
    elem : Element to count.

    Returns:
    int: Number of occurrences.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1,2],[2,3],[2,4]]
print("Count occurrences:", count_occurrences(lst, 2))

Count occurrences: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep
flatten(lst) that takes a deeply nested list lst and returns a single
f
lattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].


In [135]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
    lst (list): Deeply nested list.

    Returns:
    list: Fully flattened list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

lst = [[[1,2],[3,4]],[[5,6],[7,8]]]
print("Deep flatten:", deep_flatten(lst))

Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average
of all the elements.
nested(lst) that takes a nested list lst and returns the average

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5

In [136]:
def average_nested(lst):
    """
    Calculate the average of all numbers in a nested list.

    Parameters:
    lst (list): Nested list.

    Returns:
    float: Average of all elements.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

lst = [[1,2],[3,4],[5,6]]
print("Average nested:", average_nested(lst))

Average nested: 3.5


## To- Do- NumPy

### Basic Vector and Matrix Operation with Numpy.


In [137]:
import numpy as np

Problem- 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.


In [138]:
arr1 = np.empty((2,2))
print("Empty array:\n", arr1)

Empty array:
 [[2.   1.  ]
 [1.75 0.75]]


2. Initialize an all one array with size 4X2.

In [139]:
arr2 = np.ones((4,2))
print("\nOnes array:\n", arr2)


Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [140]:
arr3 = np.full((3,3), 7)
print("\nFull array:\n", arr3)


Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [141]:
arr4 = np.zeros_like(arr2)
print("\nZeros like array:\n", arr4)


Zeros like array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [142]:
arr5 = np.ones_like(arr1)
print("\nOnes like array:\n", arr5)


Ones like array:
 [[1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [143]:
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nList converted to array:\n", arr6)


List converted to array:
 [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [144]:
arr = np.arange(10,50)
print("\nArray 10-49:\n", arr)


Array 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [145]:
matrix = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix)


3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [146]:
identity = np.eye(3)
print("\nIdentity Matrix:\n", identity)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [147]:
rand_arr = np.random.random(30)
print("\nMean:", rand_arr.mean())


Mean: 0.4445196010663108


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [148]:
rand_matrix = np.random.random((10,10))
print("\nMin:", rand_matrix.min())
print("Max:", rand_matrix.max())


Min: 0.0007452023888712134
Max: 0.9782744675716086


6. Create a zero array of size 10 and replace 5th element with 1.


In [149]:
arr = np.zeros(10)
arr[4] = 1
print("\nModified array:\n", arr)


Modified array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [150]:
arr = np.array([1,2,0,0,4,0])
print("\nReversed:", arr[::-1])


Reversed: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [151]:
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder array:\n", border)


Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [152]:
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print("\nCheckerboard:\n", checker)


Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem- 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.


In [153]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print("\nAddition:\n", x+y)
print("\nSubtraction:\n", x-y)
print("\nMultiply by 3:\n", x*3)
print("\nSquare:\n", x**2)


Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [154]:
# Dot products
print("\nDot v and w:", np.dot(v,w))
print("Dot x and v:", np.dot(x,v))
print("Dot x and y:\n", np.dot(x,y))


Dot v and w: 219
Dot x and v: [29 77]
Dot x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.


In [155]:
# Concatenate
print("\nConcatenate x and y (rows):\n", np.concatenate((x,y), axis=0))
print("\nConcatenate v and w (column):\n", np.vstack((v,w)))


Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (column):
 [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [156]:
# 7. Concatenate x and v
# print("\nConcatenate x and v:\n", np.concatenate((x,v)))
# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:
x is a 2-dimensional array (2×2 matrix) while v is a 1-dimensional vector, so their dimensions do not match for concatenation.

Problem- 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB̸ = BA.
3. Prove (AB)T = BTAT.


In [157]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("\nA * A^-1:\n", np.dot(A, A_inv))

# 2. Show AB != BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x −3y+z =−1

x −y+2z =−3

3x +y−z =9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [158]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("\nSolution [x,y,z]:\n", X)


Solution [x,y,z]:
 [ 2.  1. -2.]


### Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

In [159]:
import numpy as np
import time



1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
and Print the time taken for this operation.



In [160]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python List Addition Time:", end - start, "seconds")

Python List Addition Time: 0.11970281600952148 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.



In [161]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy Addition Time:", end - start, "seconds")

NumPy Addition Time: 0.017711400985717773 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
Measure and Print the time taken for this operation.



In [162]:
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")

Python List Multiplication Time: 0.11423468589782715 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.



In [163]:
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy Multiplication Time:", end - start, "seconds")

NumPy Multiplication Time: 0.016668081283569336 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
Print the time taken for this operation.



In [164]:
start = time.time()

dot_product = sum(list1[i] * list2[i] for i in range(size))

end = time.time()

print("Python Dot Product Time:", end - start, "seconds")

Python Dot Product Time: 0.11340594291687012 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.



In [165]:
start = time.time()

dot_product = np.dot(arr1, arr2)

end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")

NumPy Dot Product Time: 0.002577066421508789 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.



In [166]:
size = 1000

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(size))
           for j in range(size)]
           for i in range(size)]

end = time.time()

print("Python Matrix Multiplication Time:", end - start, "seconds")

Python Matrix Multiplication Time: 117.88436079025269 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation

In [167]:
size = 1000

A = np.ones((size,size))
B = np.ones((size,size))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

NumPy Matrix Multiplication Time: 0.08682441711425781 seconds
